Extract data file,
Version = 2.4,
First year: ,2024
Final year: ,2050
File format: ,2
Transpose years down rows: ,0
Recalculate projection: ,1
Force full precision: ,0
Save recalculated projection: ,0
Extract costs in local currency: ,0
Download all demographic country data as needed: ,1
Force sensitivity bounds for LiST: ,0
Run LiST Uncertainty Analysis: ,0
LiST Uncertainty Analysis iterations: ,144
Extract LiST Uncertainty Analysis data: ,0
Update default AIM data: ,0
Calculate AIDS impacts indicators: ,0
Export UA info: ,0
Run AIM Uncertainty Analysis: ,0
AIM Uncertainty Analysis iterations: ,0
Data list: ,0
Data list defaults: ,1
AIM inputs: ,0
DHIS2: ,0
Number of chosen projections: ,1
Chosen projections,
,C:\Users\Administrator\Documents\AFG_cr1_baseline.PJNZ
Number of selected indicators: ,0
